!!example.guice.module.CassandraModule$CassandraStorage
cluster: Nebula Cassandra Cluster
hosts: [localhost]
keyspace: Twissjava
port: 9160
replicationFactor: 1
readConsistencyLevel: QUORUM
writeConsistencyLevel: QUORUM
